// ======= DO NOT EDIT THIS FILE ============

class Node {

    Worker info;
    Node left, right;
    int bal, level;

    Node() {
    }

    Node(Worker x) {
        info = x;
        left = right = null;
    }
}
